`include_once`の説明の修正
php/doc-ja pull request #128
Opened 2024-09-26 19:53 UTC by takaram

https://github.com/php/doc-en/pull/3790 を日本語版に反映しています。

また、ついでにはなりますが、[原文](https://github.com/php/doc-en/blob/c8564726a0289d0d685fad368df1ff15c292ff3d/language/control-structures/include-once.xml#L10-L13)と比較して日本語訳がやや異なっている部分を修正しています。

- 原文の"include_once returns true."の部分は前の文から続いており、「既に読み込まれている場合」の説明の一部であるはず
- 「重要な違い」というニュアンスは原文にはなさそう

2024-09-29 13:49 UTC, youkidearitai approved these changes
ありがとうございます！
確かに `include` は式なのでLGTMです！

一応 @mumumu さんも確認いただけますでしょうか？

2024-10-24 17:12 UTC, Girgias requested changes
The `<!-- EN-Revision: af6fdf16ab44bcf4d045407963e43c3d9dd2ff29 Maintainer: takagi Status: ready -->` needs to be updated.

I am guessing it is `89d80c92a1154a2903fff371f0d056bf2ac8ba27` looking at https://doc.php.net/revcheck.php?p=plain&lang=ja&hbp=af6fdf16ab44bcf4d045407963e43c3d9dd2ff29&f=language/control-structures/include-once.xml&c=on

2024-10-26 00:51 UTC, takaram commented
@Girgias 
Ah, you are right! Thank you :)

2024-10-26 01:09 UTC, Girgias approved these changes

2024-10-26 01:10 UTC, merged

2024-10-26 01:11 UTC, Girgias commented
The build is broken because https://github.com/php/doc-ja/pull/135 needs to be merged (and checked that it properly syncs the COM FAQ)